#!/bin/bash

#set -x

usage() {
    echo "Usage: $0 <database type>"
    echo "     : database type -> postgres | sqlserver | mysql | sqlite"
    exit
}


case $1 in
    postgres)
        source .envpostgres
        uvicorn main:app --host 0.0.0.0 --port 8001
        ;;
    mysql)
        source .envmysql
        uvicorn main:app --host 0.0.0.0 --port 8001
        #uvicorn main:app --host 0.0.0.0 --port 8002
        ;;
    sqlite)
        source .envsqlite
        uvicorn main:app --host 0.0.0.0 --port 8001
        #uvicorn main:app --host 0.0.0.0 --port 8003
        ;;
    sqlserver)
        source .envsqlserver
        uvicorn main:app --host 0.0.0.0 --port 8004
        ;;
    *)
        usage
        ;;
esac
exit 0

